// Local manual QA only. Not part of the static deployment archive.
import http from 'node:http';
import{serveStatic}from '../static-server.js';
import{readFile}from 'node:fs/promises';
import{resolve,extname}from 'node:path';
import{STAGES,SCENES,TREASURE_SCENES}from '../dist/engine.js';
import{startupFault,startupPage}from './startup-audit.js';
const root=resolve('dist');
http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'),path=decodeURIComponent(url.pathname);if(startupFault(req,res,path))return;if(path==='/'&&url.searchParams.has('startup')){res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(startupPage(await readFile(resolve(root,'index.html'),'utf8'),url.searchParams.get('startup')));return;}if(path==='/puzzle-audit'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(await readFile('tests/puzzle-audit.html','utf8'));return;}if(path==='/media-audit'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(await readFile('tests/media-audit.html','utf8'));return;}if(path==='/audit'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(await readFile('tests/scene-audit.html','utf8'));return;}if(path==='/'&&url.searchParams.has('stage')){const stage=Math.max(0,Math.min(10,Number(url.searchParams.get('stage'))||0)),scene=STAGES[stage].scene,all=TREASURE_SCENES,bonus=url.searchParams.get('bonus'),s={version:2,stage,scene,player:url.searchParams.get('at')==='spawn'?{...SCENES[scene].spawn}:url.searchParams.get('at')==='chest'&&SCENES[scene].chest?{x:SCENES[scene].chest.x+22,y:SCENES[scene].chest.y+5}:{x:STAGES[stage].x,y:STAGES[stage].y+25},elapsed:0,empathy:stage>=6,collectibles:[],treasures:bonus==='ready'?all:[],records:{},completed:stage===10&&url.searchParams.get('movie')==='completion',endingPending:stage===10&&url.searchParams.get('movie')==='completion',completionVideoPending:stage===10&&url.searchParams.get('movie')==='completion',storyPending:url.searchParams.get('story')};let html=await readFile(resolve(root,'index.html'),'utf8');html=html.replace('<script src="boot.js" defer></script>',`<script>localStorage.setItem('moon-chase-save-v1',${JSON.stringify(JSON.stringify(s))});</script><script src="boot.js" defer></script>`);if(url.searchParams.has('intro'))html=html.replace(/localStorage\.setItem\([^<]+;/,"localStorage.removeItem('moon-chase-save-v1');");res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html);return;}if(path.endsWith('.mp4')&&Number(process.env.QA_VIDEO_DELAY_MS)>0){setTimeout(()=>serveStatic(req,res,root),Number(process.env.QA_VIDEO_DELAY_MS));return;}serveStatic(req,res,root);}catch{res.writeHead(404).end();}}).listen(4174,'127.0.0.1',()=>console.log('QA: http://localhost:4174/?stage=1'));
